### PR TITLE
API adjustments, Debian packaging

### PR DESCRIPTION
**Pull request by ptomato**
https://phabricator.endlessm.com/T14916

### CODE REVIEW

**Comment by tchx84** [comment]
@ptomato Installed the hotdoc package, and built/installed this package properly:

```
ii  python3-hotdoc                        0.8.90.1-1bem1                                amd64        tastiest documentation tool
ii  python3-hotdoc-modular-framework      0.0.0-1                                       all          Hotdoc modular framework extension
```

But, when I try to build the docs for e-k-l (branch T14916) I get the following error:

```
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/hotdoc/run_hotdoc.py", line 267, in execute_command
    res = app.run()
  File "/usr/lib/python3/dist-packages/hotdoc/run_hotdoc.py", line 97, in run
    self.project.format(self.link_resolver, self.output)
  File "/usr/lib/python3/dist-packages/hotdoc/core/project.py", line 202, in format
    self.tree.format(link_resolver, output, self.extensions)
  File "/usr/lib/python3/dist-packages/hotdoc/core/tree.py", line 693, in format
    self.format_page(page, link_resolver, output, extensions)
  File "/usr/lib/python3/dist-packages/hotdoc/core/tree.py", line 678, in format_page
    extension.format_page(page, link_resolver, output)
  File "/usr/lib/python3/dist-packages/hotdoc/core/project.py", line 65, in format_page
    page, link_resolver, output)
  File "/usr/lib/python3/dist-packages/hotdoc/core/extension.py", line 500, in format_page
    page.format(self.formatter, link_resolver, output, actual_output)
  File "/usr/lib/python3/dist-packages/hotdoc/core/tree.py", line 290, in format
    formatter.write_page(self, root, output)
  File "/usr/lib/python3/dist-packages/hotdoc/core/formatter.py", line 408, in write_page
    self.__copy_extra_files(build_root, os.path.dirname(full_path))
  File "/usr/lib/python3/dist-packages/hotdoc/core/formatter.py", line 253, in __copy_extra_files
    self.__copy_assets(os.path.join(root, 'html', 'assets'))
  File "/usr/lib/python3/dist-packages/hotdoc/core/formatter.py", line 236, in __copy_assets
    extra_files = self._get_extra_files()
  File "/usr/lib/python3/dist-packages/hotdoc/core/formatter.py", line 848, in _get_extra_files
    res.extend(self.__get_theme_files(self.theme_path))
  File "/usr/lib/python3/dist-packages/hotdoc/core/formatter.py", line 835, in __get_theme_files
    theme_files = os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/hotdoc/hotdoc_bootstrap_theme/dist'
```

That path certainly doesn't exist. Checked the files provided by these packages via `dpkg -L python3-hotdoc | grep hotdoc_bootstrap_theme` and `dpkg -L python3-hotdoc-modular-framework | grep hotdoc_bootstrap_theme` 

I suspect this could be a bug with the hotdoc packaging fles, or... maybe the missing file is supposed to be provided via another package we didn't add to OBS?

Asking just to make sure this isn't something related to this PR.

**Comment by ptomato** [comment]
If you grab my branch of `hotdoc` from OBS then you should be able to try again now. Otherwise it'll hopefully be merged soon.

**Comment by xjuan** [comment]
CR Pass, only need to check if debian package builds

**Comment by ptomato** [comment]
Needed one small adjustment to adapt to a quirk in jenkins-obs-build.

**Pull request merged**
